### ISSUE TITLE
Text of game config buttons

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-dlls#18] opened 2018-05-25 21:06 UTC
At the moment we don't know how to change the texts on the buttons on the config screen. You know, the "ON", "OFF", "Show menu", "Hide window" etc.

There are 3 reasons why we want to be able to change these:
1. We want to change the Character sprites options from Original/Updated to PS3/MangaGamer.
2. The resolution options at the bottom are wrong as they're still 4:3 instead of 16:9.
3. Lately people who are translating Higurashi to other languages are showing up on Discord.

Currently we don't have any idea where these texts are stored. If it is somewhere in the DLL then it would be another candidate for JSON configuration. If it is elsewhere then we'll decide based on the actual location.

**Comment by ghost** [comment] 2018-05-29 01:10
These do not appear to be hard-coded into the DLL - at least, not in any way that I've been able to discover so far.  In fact, at a glance I'm having a hard time even seeing where it even pulls that text from.  I can see the button logic, but not anything related to visuals except for controlling fade in and out etc.  It might be worth having someone else check out assets to see if it's an easy find elsewhere.

**Comment by enumag** [comment] 2018-05-29 04:33
The reason why I wrote this issue is that we were unable to find these texts in the assets file. They might still be hidden there somewhere but we have no idea where. They are definitely not easy to find.

**Comment by TellowKrinkle** [comment] 2018-08-21 04:18
`sharedassets0.assets` contains strings that match the menu items, and if you edit them in a hex editor to other strings of equal length it does update the ones in the menu in game, so I would guess those are what's controlling them.
```
> grep -r "Show Menu" /Applications/Games/Higurashi\ When\ They\ Cry\ Hou\ -\ Ch.2\ Watanagashi.app/Contents/Resources/Data
Binary file /Applications/Games/Higurashi When They Cry Hou - Ch.2 Watanagashi.app/Contents/Resources/Data/sharedassets0.assets matches
```

**Comment by enumag** [comment] 2018-08-21 05:00
The problem is we need to be able to change the strings to longer values. That can't be done with hex edit, right?

Doddler gave us a tip how to possibly hack it in DLL though: https://github.com/07th-mod/watanagashi/issues/82#issuecomment-411224336

**Comment by TellowKrinkle** [comment] 2018-08-21 19:11
Right, but I would guess you can do it with a program that can properly edit a unity assets file, assuming one exists.
I just used the hex editor editing to show that those really were the strings that controlled the buttons.

**Comment by enumag** [comment] 2018-08-21 19:36
We're using [UABE](https://github.com/DerPopo/UABE) to extract and replace images in the unity assets file but so far we ware unable to change the text values with this program. Maybe we're doing it wrong or maybe it's not supported - we don't know.

**Comment by TellowKrinkle** [comment] 2018-08-22 01:13
Alright it looks like the issue is with UABE's parsing of the asset file.  Here's my horrible workaround:

1. Use a hex editor to find the text you want to edit.  There'll usually be multiple instances of it, choose the one that's right before some Japanese text meaning the same thing <img width="577" src="https://user-images.githubusercontent.com/3315070/44436424-b10fdc80-a57a-11e8-9033-a3badb5c4aad.png">
2. Record the offset of the text block (or any offset inside of the text), in the case of this example,  `0x499E7F8` will work.
3. Use [this python script](https://gist.github.com/tellowkrinkle/88fb6a4c0e2132fba0185d631426f65f) which searches through the list of objects in the assets file and finds the object ID of the object that spans that offset.  You can do multiple at a time by putting them into a file like this (the names will be repeated back to help you figure out what's what).  You'll need to `pip install unitypack` to use the script.: <img width="448" src="https://user-images.githubusercontent.com/3315070/44436602-c0435a00-a57b-11e8-8f1b-42e2e03d76f8.png">
4. Take the object ID you got from the python script and use UABE to `Export Raw` that object.
5. Open the raw data in a hex editor and modify the string.  The four bytes before the string are a little endian 32-bit length, and the string is padded to a multiple of four bytes. <img width="383" alt="3" src="https://user-images.githubusercontent.com/3315070/44436895-3d230380-a57d-11e8-8367-f5be1ac89774.png">
6. Use UABE to `Import Raw` the edited file
7. Save the new assets file
8. Use it in the game (and yes I realized after making this that I changed the wrong button to `MangaGamer`) <img width="781" alt="image" src="https://user-images.githubusercontent.com/3315070/44437015-b4f12e00-a57d-11e8-82aa-4120b2f5d8df.png">

**Comment by enumag** [comment] 2018-08-22 05:03
Wow, that's quite impressive. Too complicated for me, I never worked with either hex editor or with python and there are quite a few strings we would need to upgrade in like 14 different assets file so I don't think I'd be able to get it right anyway. Still it's nice to know it's possible, maybe we'll find a better way in the future.

Could you try to report the bug to UABE? You should be able to provide some details about what's wrong there.

**Comment by enumag** [comment] 2018-08-22 05:07
Actually... would it be possible to write a script that would both find and replace the text? Like changing both the little endian value and the text itself? Of course we would need to come up with some indicator which instance of the text should be changed. But considering how many different assets files we have, I don't think it's feasible to replace them unless it's automatized as a command line script.

**Comment by TellowKrinkle** [comment] 2018-08-22 05:33
Since UABE is closed source I don't actually know exactly what's going wrong in it, only that it exhibits the same symptoms as UnityPack (the python library I'm using) which I would guess is somehow misreading the type information (though I haven't looked into how that works, I just know that the decisions it makes based on the type information it read causes it to only read the first 32 bytes of data rather than the whole thing).  I'll look over UnityPack's type parser a little later and then make the issues.

As for making a script, I should be able to make a script that takes a list of script changes to make and outputs a bunch of files to inject using UABE.  UnityPack is sadly extraction only though, so you will need to do the final step with UABE.

**Comment by enumag** [comment] 2018-08-22 07:20
That sounds rather complicated. Maybe you could try some DLL hacking using the recommendation from Doddler I linked above before delving into custom python script? It might be easier to do it that way. Basically the goal is to hijack the values after they are loaded from the assets and update them there in the DLL. If that works we won't need any custom script or UABE. It would be a dirtier solution but much less amount of work. What do you think?

**Comment by TellowKrinkle** [comment] 2018-08-22 15:42
I could look into that in a bit.

For now, I did finish a script that does everything except actually inject the files [here](https://gist.github.com/tellowkrinkle/5f8f45b9fb62356257b46457594654f9).  Make a JSON file of the edits you want to make like this: 
<img width="371" src="https://user-images.githubusercontent.com/3315070/44474172-a5163000-a5f7-11e8-9059-6a7d8a43cee6.png">
Then, call the python file with `python3 UnityTextModifier.py sharedassets0.assets myJSONFile.json outputFolder`.  It'll put a bunch of numbered `.dat` files into the output folder, which you can then `Import Raw` into the corresponding objects in UABE.

**Comment by enumag** [comment] 2018-08-22 15:51
off topic: Do you have any idea how to make a script to replace an object in the assets? If we could somehow automatize image replacement in the assets, it would be a huge help

**Comment by TellowKrinkle** [comment] 2018-08-22 15:56
It appears UABE has an API so let me look into that

**Comment by enumag** [comment] 2018-08-22 15:58
Ok, if you can manage to do something about that, create a separate issue for it please. Thank you!

**Comment by ghost** [comment] 2018-08-22 17:06
Just speculation, but some of the issues we are seeing may stem from Higurashi using an older version of Unity.  Perhaps some of these asset tools have a customizable Unity compatibility setting, or older versions that support that older version.  Or perhaps there is no version breaking change or the version information is already included in or derived from the asset file contents and so it's irrelevant to these issues.  But maybe something worth thinking about or looking into.

**Comment by TellowKrinkle** [comment] 2018-08-22 17:06
Alright, apparently the UABE API is actually for making plugins and is a painful-looking Windows C++ API that needs Visual Studio to compile.  On the other hand, its EMIP files (which are files which contain a list of edits to make) don't look too hard to generate.  What's the current workflow for editing an image and how would you want it automated?

When creating a separate issue, should I create an issue on this (higurashi-dlls) repo or is there another one which would make more sense?

**Comment by enumag** [comment] 2018-08-22 17:09
Create the issue here, it's sort of our meta-repo.

https://github.com/07th-mod/higurashi-patch-compiler/issues

**Comment by enumag** [comment] 2018-08-22 18:52
The current workflow is that we have a zip of images we need to replace. For each new chapter we open UABE, load the assets, then go through all the texture files that need to be replaced, click Plugins, Edit, select ARBG32 to avoid transparency issues, click Load, select the replacement file. In total there are over 30 images to replace. And then we need to repeat the process for mac assets because they are different from windows assets. It's doable, but requires a lot of clicking and it's easy to do some mistake like not selecting ARBG32 in one of the 30 cases.

Having it automated would be more reliable and would save us a lot of time. Ideally it should work like "select assets file", "select directory with replacement PNGs" => replace all PNGs with matching names in the assets.

If we could also link a JSON file with strings to replace it would be really epic.

I don't really expect you to solve everything, I'm just telling you the ideal state. It's all up to you what you try to make. Thanks for trying!

**Comment by ghost** [comment] 2019-01-30 04:44
This issue is pretty old and I kinda stopped following once enumag and tellow started running with it.  So quick status check - is this issue up to date? still pertinent? Has anything relevant changed in the meantime?

**Comment by TellowKrinkle** [comment] 2019-01-30 06:39
Wait this is still open?  Given that the latest releases have a bunch of button texts changed I think we can close this.

For that matter I think everything described in enumag's last comment is implemented.

**Closed as completed** 2019-01-30 06:39 UTC
Labels: medium-priority, hard

**Comment by enumag** [comment] 2019-01-30 08:54
Yeah it's indeed all implemented in https://github.com/07th-mod/ui-editing-scripts. I just forgot to close this.
